//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalGalvaniMobile.IntegracaoGruppo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaMenuResponse", Namespace="http://schemas.datacontract.org/2004/07/DTO.Menu")]
    [System.SerializableAttribute()]
    public partial class ListaMenuResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.Menu[] MenusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.Menu[] Menus {
            get {
                return this.MenusField;
            }
            set {
                if ((object.ReferenceEquals(this.MenusField, value) != true)) {
                    this.MenusField = value;
                    this.RaisePropertyChanged("Menus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Menu", Namespace="http://schemas.datacontract.org/2004/07/DTO.Menu")]
    [System.SerializableAttribute()]
    public partial class Menu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.Menu.MenuComplemento ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.MenuIdiomaExcecao DetalheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IconClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MenuPaiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MenuTipoAcaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MenuTipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PublicacaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RotuloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.Menu.MenuComplemento Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.MenuIdiomaExcecao Detalhe {
            get {
                return this.DetalheField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheField, value) != true)) {
                    this.DetalheField = value;
                    this.RaisePropertyChanged("Detalhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IconClass {
            get {
                return this.IconClassField;
            }
            set {
                if ((object.ReferenceEquals(this.IconClassField, value) != true)) {
                    this.IconClassField = value;
                    this.RaisePropertyChanged("IconClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageURL {
            get {
                return this.ImageURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageURLField, value) != true)) {
                    this.ImageURLField = value;
                    this.RaisePropertyChanged("ImageURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkURL {
            get {
                return this.LinkURLField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkURLField, value) != true)) {
                    this.LinkURLField = value;
                    this.RaisePropertyChanged("LinkURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((this.MenuIdField.Equals(value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MenuPaiId {
            get {
                return this.MenuPaiIdField;
            }
            set {
                if ((this.MenuPaiIdField.Equals(value) != true)) {
                    this.MenuPaiIdField = value;
                    this.RaisePropertyChanged("MenuPaiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MenuTipoAcaoId {
            get {
                return this.MenuTipoAcaoIdField;
            }
            set {
                if ((this.MenuTipoAcaoIdField.Equals(value) != true)) {
                    this.MenuTipoAcaoIdField = value;
                    this.RaisePropertyChanged("MenuTipoAcaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MenuTipoId {
            get {
                return this.MenuTipoIdField;
            }
            set {
                if ((this.MenuTipoIdField.Equals(value) != true)) {
                    this.MenuTipoIdField = value;
                    this.RaisePropertyChanged("MenuTipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posicao {
            get {
                return this.PosicaoField;
            }
            set {
                if ((this.PosicaoField.Equals(value) != true)) {
                    this.PosicaoField = value;
                    this.RaisePropertyChanged("Posicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PublicacaoId {
            get {
                return this.PublicacaoIdField;
            }
            set {
                if ((this.PublicacaoIdField.Equals(value) != true)) {
                    this.PublicacaoIdField = value;
                    this.RaisePropertyChanged("PublicacaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rotulo {
            get {
                return this.RotuloField;
            }
            set {
                if ((object.ReferenceEquals(this.RotuloField, value) != true)) {
                    this.RotuloField = value;
                    this.RaisePropertyChanged("Rotulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((this.TargetIdField.Equals(value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Menu.MenuComplemento", Namespace="http://schemas.datacontract.org/2004/07/DTO.Menu")]
        [System.SerializableAttribute()]
        public partial class MenuComplemento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ListaUsuarioField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ListaUsuarioGrupoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool PrivadoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ListaUsuario {
                get {
                    return this.ListaUsuarioField;
                }
                set {
                    if ((object.ReferenceEquals(this.ListaUsuarioField, value) != true)) {
                        this.ListaUsuarioField = value;
                        this.RaisePropertyChanged("ListaUsuario");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ListaUsuarioGrupo {
                get {
                    return this.ListaUsuarioGrupoField;
                }
                set {
                    if ((object.ReferenceEquals(this.ListaUsuarioGrupoField, value) != true)) {
                        this.ListaUsuarioGrupoField = value;
                        this.RaisePropertyChanged("ListaUsuarioGrupo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool Privado {
                get {
                    return this.PrivadoField;
                }
                set {
                    if ((this.PrivadoField.Equals(value) != true)) {
                        this.PrivadoField = value;
                        this.RaisePropertyChanged("Privado");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuIdiomaExcecao", Namespace="http://schemas.datacontract.org/2004/07/DTO.Menu")]
    [System.SerializableAttribute()]
    public partial class MenuIdiomaExcecao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdiomaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MenuIdiomaExcecaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RotuloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdiomaId {
            get {
                return this.IdiomaIdField;
            }
            set {
                if ((this.IdiomaIdField.Equals(value) != true)) {
                    this.IdiomaIdField = value;
                    this.RaisePropertyChanged("IdiomaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((this.MenuIdField.Equals(value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MenuIdiomaExcecaoId {
            get {
                return this.MenuIdiomaExcecaoIdField;
            }
            set {
                if ((this.MenuIdiomaExcecaoIdField.Equals(value) != true)) {
                    this.MenuIdiomaExcecaoIdField = value;
                    this.RaisePropertyChanged("MenuIdiomaExcecaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rotulo {
            get {
                return this.RotuloField;
            }
            set {
                if ((object.ReferenceEquals(this.RotuloField, value) != true)) {
                    this.RotuloField = value;
                    this.RaisePropertyChanged("Rotulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Arquivo", Namespace="http://schemas.datacontract.org/2004/07/DTO.Arquivo")]
    [System.SerializableAttribute()]
    public partial class Arquivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArquivoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Base64Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListaCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PastaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TamanhoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArquivoId {
            get {
                return this.ArquivoIdField;
            }
            set {
                if ((this.ArquivoIdField.Equals(value) != true)) {
                    this.ArquivoIdField = value;
                    this.RaisePropertyChanged("ArquivoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Base64 {
            get {
                return this.Base64Field;
            }
            set {
                if ((object.ReferenceEquals(this.Base64Field, value) != true)) {
                    this.Base64Field = value;
                    this.RaisePropertyChanged("Base64");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Legenda {
            get {
                return this.LegendaField;
            }
            set {
                if ((object.ReferenceEquals(this.LegendaField, value) != true)) {
                    this.LegendaField = value;
                    this.RaisePropertyChanged("Legenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListaCategoria {
            get {
                return this.ListaCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaCategoriaField, value) != true)) {
                    this.ListaCategoriaField = value;
                    this.RaisePropertyChanged("ListaCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PastaId {
            get {
                return this.PastaIdField;
            }
            set {
                if ((this.PastaIdField.Equals(value) != true)) {
                    this.PastaIdField = value;
                    this.RaisePropertyChanged("PastaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tamanho {
            get {
                return this.TamanhoField;
            }
            set {
                if ((this.TamanhoField.Equals(value) != true)) {
                    this.TamanhoField = value;
                    this.RaisePropertyChanged("Tamanho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Publicacao", Namespace="http://schemas.datacontract.org/2004/07/DTO.Publicacao")]
    [System.SerializableAttribute()]
    public partial class Publicacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.Publicacao.PublicacaoHistoricoItem[] AprovacaoHistoricoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArquivoDestaqueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.Publicacao.PublicacaoComplemento ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConteudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataAprovacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataValidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> DestaqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.PublicacaoIdiomaExcecao DetalheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EditoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FonteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PosicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublicacaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublicacaoTipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> UsuarioElegivelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.Publicacao.PublicacaoHistoricoItem[] AprovacaoHistorico {
            get {
                return this.AprovacaoHistoricoField;
            }
            set {
                if ((object.ReferenceEquals(this.AprovacaoHistoricoField, value) != true)) {
                    this.AprovacaoHistoricoField = value;
                    this.RaisePropertyChanged("AprovacaoHistorico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArquivoDestaqueId {
            get {
                return this.ArquivoDestaqueIdField;
            }
            set {
                if ((this.ArquivoDestaqueIdField.Equals(value) != true)) {
                    this.ArquivoDestaqueIdField = value;
                    this.RaisePropertyChanged("ArquivoDestaqueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.Publicacao.PublicacaoComplemento Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conteudo {
            get {
                return this.ConteudoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConteudoField, value) != true)) {
                    this.ConteudoField = value;
                    this.RaisePropertyChanged("Conteudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataAprovacao {
            get {
                return this.DataAprovacaoField;
            }
            set {
                if ((this.DataAprovacaoField.Equals(value) != true)) {
                    this.DataAprovacaoField = value;
                    this.RaisePropertyChanged("DataAprovacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataValidade {
            get {
                return this.DataValidadeField;
            }
            set {
                if ((this.DataValidadeField.Equals(value) != true)) {
                    this.DataValidadeField = value;
                    this.RaisePropertyChanged("DataValidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Destaque {
            get {
                return this.DestaqueField;
            }
            set {
                if ((this.DestaqueField.Equals(value) != true)) {
                    this.DestaqueField = value;
                    this.RaisePropertyChanged("Destaque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.PublicacaoIdiomaExcecao Detalhe {
            get {
                return this.DetalheField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheField, value) != true)) {
                    this.DetalheField = value;
                    this.RaisePropertyChanged("Detalhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EditoriaId {
            get {
                return this.EditoriaIdField;
            }
            set {
                if ((this.EditoriaIdField.Equals(value) != true)) {
                    this.EditoriaIdField = value;
                    this.RaisePropertyChanged("EditoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fonte {
            get {
                return this.FonteField;
            }
            set {
                if ((object.ReferenceEquals(this.FonteField, value) != true)) {
                    this.FonteField = value;
                    this.RaisePropertyChanged("Fonte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Posicao {
            get {
                return this.PosicaoField;
            }
            set {
                if ((this.PosicaoField.Equals(value) != true)) {
                    this.PosicaoField = value;
                    this.RaisePropertyChanged("Posicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublicacaoId {
            get {
                return this.PublicacaoIdField;
            }
            set {
                if ((this.PublicacaoIdField.Equals(value) != true)) {
                    this.PublicacaoIdField = value;
                    this.RaisePropertyChanged("PublicacaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublicacaoTipoId {
            get {
                return this.PublicacaoTipoIdField;
            }
            set {
                if ((this.PublicacaoTipoIdField.Equals(value) != true)) {
                    this.PublicacaoTipoIdField = value;
                    this.RaisePropertyChanged("PublicacaoTipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resumo {
            get {
                return this.ResumoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumoField, value) != true)) {
                    this.ResumoField = value;
                    this.RaisePropertyChanged("Resumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> UsuarioElegivel {
            get {
                return this.UsuarioElegivelField;
            }
            set {
                if ((this.UsuarioElegivelField.Equals(value) != true)) {
                    this.UsuarioElegivelField = value;
                    this.RaisePropertyChanged("UsuarioElegivel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Publicacao.PublicacaoComplemento", Namespace="http://schemas.datacontract.org/2004/07/DTO.Publicacao")]
        [System.SerializableAttribute()]
        public partial class PublicacaoComplemento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string DataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Nullable<System.DateTime> DataLiberadoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string EditoriaField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string HoraField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Nullable<bool> LiberadoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ListaUsuarioField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ListaUsuarioGrupoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Nullable<bool> PrivadoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PublicacaoTipoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Data {
                get {
                    return this.DataField;
                }
                set {
                    if ((object.ReferenceEquals(this.DataField, value) != true)) {
                        this.DataField = value;
                        this.RaisePropertyChanged("Data");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<System.DateTime> DataLiberado {
                get {
                    return this.DataLiberadoField;
                }
                set {
                    if ((this.DataLiberadoField.Equals(value) != true)) {
                        this.DataLiberadoField = value;
                        this.RaisePropertyChanged("DataLiberado");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Editoria {
                get {
                    return this.EditoriaField;
                }
                set {
                    if ((object.ReferenceEquals(this.EditoriaField, value) != true)) {
                        this.EditoriaField = value;
                        this.RaisePropertyChanged("Editoria");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Hora {
                get {
                    return this.HoraField;
                }
                set {
                    if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                        this.HoraField = value;
                        this.RaisePropertyChanged("Hora");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<bool> Liberado {
                get {
                    return this.LiberadoField;
                }
                set {
                    if ((this.LiberadoField.Equals(value) != true)) {
                        this.LiberadoField = value;
                        this.RaisePropertyChanged("Liberado");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ListaUsuario {
                get {
                    return this.ListaUsuarioField;
                }
                set {
                    if ((object.ReferenceEquals(this.ListaUsuarioField, value) != true)) {
                        this.ListaUsuarioField = value;
                        this.RaisePropertyChanged("ListaUsuario");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ListaUsuarioGrupo {
                get {
                    return this.ListaUsuarioGrupoField;
                }
                set {
                    if ((object.ReferenceEquals(this.ListaUsuarioGrupoField, value) != true)) {
                        this.ListaUsuarioGrupoField = value;
                        this.RaisePropertyChanged("ListaUsuarioGrupo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<bool> Privado {
                get {
                    return this.PrivadoField;
                }
                set {
                    if ((this.PrivadoField.Equals(value) != true)) {
                        this.PrivadoField = value;
                        this.RaisePropertyChanged("Privado");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PublicacaoTipo {
                get {
                    return this.PublicacaoTipoField;
                }
                set {
                    if ((object.ReferenceEquals(this.PublicacaoTipoField, value) != true)) {
                        this.PublicacaoTipoField = value;
                        this.RaisePropertyChanged("PublicacaoTipo");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Publicacao.PublicacaoHistoricoItem", Namespace="http://schemas.datacontract.org/2004/07/DTO.Publicacao")]
        [System.SerializableAttribute()]
        public partial class PublicacaoHistoricoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string DataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Nullable<System.DateTime> DataLiberacaoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string DescricaoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string HoraField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Nullable<bool> LiberadoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NomeUsuarioField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private System.Nullable<int> UsuarioIdField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Data {
                get {
                    return this.DataField;
                }
                set {
                    if ((object.ReferenceEquals(this.DataField, value) != true)) {
                        this.DataField = value;
                        this.RaisePropertyChanged("Data");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<System.DateTime> DataLiberacao {
                get {
                    return this.DataLiberacaoField;
                }
                set {
                    if ((this.DataLiberacaoField.Equals(value) != true)) {
                        this.DataLiberacaoField = value;
                        this.RaisePropertyChanged("DataLiberacao");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Descricao {
                get {
                    return this.DescricaoField;
                }
                set {
                    if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                        this.DescricaoField = value;
                        this.RaisePropertyChanged("Descricao");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Hora {
                get {
                    return this.HoraField;
                }
                set {
                    if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                        this.HoraField = value;
                        this.RaisePropertyChanged("Hora");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<bool> Liberado {
                get {
                    return this.LiberadoField;
                }
                set {
                    if ((this.LiberadoField.Equals(value) != true)) {
                        this.LiberadoField = value;
                        this.RaisePropertyChanged("Liberado");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string NomeUsuario {
                get {
                    return this.NomeUsuarioField;
                }
                set {
                    if ((object.ReferenceEquals(this.NomeUsuarioField, value) != true)) {
                        this.NomeUsuarioField = value;
                        this.RaisePropertyChanged("NomeUsuario");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public System.Nullable<int> UsuarioId {
                get {
                    return this.UsuarioIdField;
                }
                set {
                    if ((this.UsuarioIdField.Equals(value) != true)) {
                        this.UsuarioIdField = value;
                        this.RaisePropertyChanged("UsuarioId");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicacaoIdiomaExcecao", Namespace="http://schemas.datacontract.org/2004/07/DTO.Publicacao")]
    [System.SerializableAttribute()]
    public partial class PublicacaoIdiomaExcecao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ArquivoDestaqueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConteudoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FonteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdiomaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublicacaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PublicacaoIdiomaExcecaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ArquivoDestaqueId {
            get {
                return this.ArquivoDestaqueIdField;
            }
            set {
                if ((this.ArquivoDestaqueIdField.Equals(value) != true)) {
                    this.ArquivoDestaqueIdField = value;
                    this.RaisePropertyChanged("ArquivoDestaqueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Conteudo {
            get {
                return this.ConteudoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConteudoField, value) != true)) {
                    this.ConteudoField = value;
                    this.RaisePropertyChanged("Conteudo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Editora {
            get {
                return this.EditoraField;
            }
            set {
                if ((object.ReferenceEquals(this.EditoraField, value) != true)) {
                    this.EditoraField = value;
                    this.RaisePropertyChanged("Editora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fonte {
            get {
                return this.FonteField;
            }
            set {
                if ((object.ReferenceEquals(this.FonteField, value) != true)) {
                    this.FonteField = value;
                    this.RaisePropertyChanged("Fonte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdiomaId {
            get {
                return this.IdiomaIdField;
            }
            set {
                if ((this.IdiomaIdField.Equals(value) != true)) {
                    this.IdiomaIdField = value;
                    this.RaisePropertyChanged("IdiomaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublicacaoId {
            get {
                return this.PublicacaoIdField;
            }
            set {
                if ((this.PublicacaoIdField.Equals(value) != true)) {
                    this.PublicacaoIdField = value;
                    this.RaisePropertyChanged("PublicacaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PublicacaoIdiomaExcecaoId {
            get {
                return this.PublicacaoIdiomaExcecaoIdField;
            }
            set {
                if ((this.PublicacaoIdiomaExcecaoIdField.Equals(value) != true)) {
                    this.PublicacaoIdiomaExcecaoIdField = value;
                    this.RaisePropertyChanged("PublicacaoIdiomaExcecaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resumo {
            get {
                return this.ResumoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumoField, value) != true)) {
                    this.ResumoField = value;
                    this.RaisePropertyChanged("Resumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Configuracao", Namespace="http://schemas.datacontract.org/2004/07/DTO.Configuracao")]
    [System.SerializableAttribute()]
    public partial class Configuracao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConfiguracaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoEmailPrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContatoTelefonePrincipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailDisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailPortaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostBaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkMapaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacaoComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfiguracaoId {
            get {
                return this.ConfiguracaoIdField;
            }
            set {
                if ((this.ConfiguracaoIdField.Equals(value) != true)) {
                    this.ConfiguracaoIdField = value;
                    this.RaisePropertyChanged("ConfiguracaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContatoEmailPrincipal {
            get {
                return this.ContatoEmailPrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoEmailPrincipalField, value) != true)) {
                    this.ContatoEmailPrincipalField = value;
                    this.RaisePropertyChanged("ContatoEmailPrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContatoTelefonePrincipal {
            get {
                return this.ContatoTelefonePrincipalField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatoTelefonePrincipalField, value) != true)) {
                    this.ContatoTelefonePrincipalField = value;
                    this.RaisePropertyChanged("ContatoTelefonePrincipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailDestino {
            get {
                return this.EmailDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailDestinoField, value) != true)) {
                    this.EmailDestinoField = value;
                    this.RaisePropertyChanged("EmailDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailDisplayName {
            get {
                return this.EmailDisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailDisplayNameField, value) != true)) {
                    this.EmailDisplayNameField = value;
                    this.RaisePropertyChanged("EmailDisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailHost {
            get {
                return this.EmailHostField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailHostField, value) != true)) {
                    this.EmailHostField = value;
                    this.RaisePropertyChanged("EmailHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailPassword {
            get {
                return this.EmailPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailPasswordField, value) != true)) {
                    this.EmailPasswordField = value;
                    this.RaisePropertyChanged("EmailPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailPorta {
            get {
                return this.EmailPortaField;
            }
            set {
                if ((this.EmailPortaField.Equals(value) != true)) {
                    this.EmailPortaField = value;
                    this.RaisePropertyChanged("EmailPorta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailUsername {
            get {
                return this.EmailUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailUsernameField, value) != true)) {
                    this.EmailUsernameField = value;
                    this.RaisePropertyChanged("EmailUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostBase {
            get {
                return this.HostBaseField;
            }
            set {
                if ((object.ReferenceEquals(this.HostBaseField, value) != true)) {
                    this.HostBaseField = value;
                    this.RaisePropertyChanged("HostBase");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkMapa {
            get {
                return this.LinkMapaField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkMapaField, value) != true)) {
                    this.LinkMapaField = value;
                    this.RaisePropertyChanged("LinkMapa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacao {
            get {
                return this.LocalizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacaoField, value) != true)) {
                    this.LocalizacaoField = value;
                    this.RaisePropertyChanged("Localizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalizacaoComplemento {
            get {
                return this.LocalizacaoComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacaoComplementoField, value) != true)) {
                    this.LocalizacaoComplementoField = value;
                    this.RaisePropertyChanged("LocalizacaoComplemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Banner", Namespace="http://schemas.datacontract.org/2004/07/DTO.Banner")]
    [System.SerializableAttribute()]
    public partial class Banner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArquivoId_PrimariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ArquivoId_SecundariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BannerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BannerTipoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.Banner.BannerComplemento ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataValidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PortalGalvaniMobile.IntegracaoGruppo.BannerIdiomaExcecao DetalheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PosicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TargetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalCliqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalVisualizacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArquivoId_Primaria {
            get {
                return this.ArquivoId_PrimariaField;
            }
            set {
                if ((this.ArquivoId_PrimariaField.Equals(value) != true)) {
                    this.ArquivoId_PrimariaField = value;
                    this.RaisePropertyChanged("ArquivoId_Primaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ArquivoId_Secundaria {
            get {
                return this.ArquivoId_SecundariaField;
            }
            set {
                if ((this.ArquivoId_SecundariaField.Equals(value) != true)) {
                    this.ArquivoId_SecundariaField = value;
                    this.RaisePropertyChanged("ArquivoId_Secundaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Ativo {
            get {
                return this.AtivoField;
            }
            set {
                if ((this.AtivoField.Equals(value) != true)) {
                    this.AtivoField = value;
                    this.RaisePropertyChanged("Ativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BannerId {
            get {
                return this.BannerIdField;
            }
            set {
                if ((this.BannerIdField.Equals(value) != true)) {
                    this.BannerIdField = value;
                    this.RaisePropertyChanged("BannerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BannerTipoId {
            get {
                return this.BannerTipoIdField;
            }
            set {
                if ((this.BannerTipoIdField.Equals(value) != true)) {
                    this.BannerTipoIdField = value;
                    this.RaisePropertyChanged("BannerTipoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.Banner.BannerComplemento Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataValidade {
            get {
                return this.DataValidadeField;
            }
            set {
                if ((this.DataValidadeField.Equals(value) != true)) {
                    this.DataValidadeField = value;
                    this.RaisePropertyChanged("DataValidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PortalGalvaniMobile.IntegracaoGruppo.BannerIdiomaExcecao Detalhe {
            get {
                return this.DetalheField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheField, value) != true)) {
                    this.DetalheField = value;
                    this.RaisePropertyChanged("Detalhe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkURL {
            get {
                return this.LinkURLField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkURLField, value) != true)) {
                    this.LinkURLField = value;
                    this.RaisePropertyChanged("LinkURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Posicao {
            get {
                return this.PosicaoField;
            }
            set {
                if ((this.PosicaoField.Equals(value) != true)) {
                    this.PosicaoField = value;
                    this.RaisePropertyChanged("Posicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((this.TargetIdField.Equals(value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalClique {
            get {
                return this.TotalCliqueField;
            }
            set {
                if ((this.TotalCliqueField.Equals(value) != true)) {
                    this.TotalCliqueField = value;
                    this.RaisePropertyChanged("TotalClique");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalVisualizacao {
            get {
                return this.TotalVisualizacaoField;
            }
            set {
                if ((this.TotalVisualizacaoField.Equals(value) != true)) {
                    this.TotalVisualizacaoField = value;
                    this.RaisePropertyChanged("TotalVisualizacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Banner.BannerComplemento", Namespace="http://schemas.datacontract.org/2004/07/DTO.Banner")]
        [System.SerializableAttribute()]
        public partial class BannerComplemento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string BannerTipoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool LiberadoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ListaUsuarioField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string ListaUsuarioGrupoField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private bool PrivadoField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string BannerTipo {
                get {
                    return this.BannerTipoField;
                }
                set {
                    if ((object.ReferenceEquals(this.BannerTipoField, value) != true)) {
                        this.BannerTipoField = value;
                        this.RaisePropertyChanged("BannerTipo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool Liberado {
                get {
                    return this.LiberadoField;
                }
                set {
                    if ((this.LiberadoField.Equals(value) != true)) {
                        this.LiberadoField = value;
                        this.RaisePropertyChanged("Liberado");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ListaUsuario {
                get {
                    return this.ListaUsuarioField;
                }
                set {
                    if ((object.ReferenceEquals(this.ListaUsuarioField, value) != true)) {
                        this.ListaUsuarioField = value;
                        this.RaisePropertyChanged("ListaUsuario");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string ListaUsuarioGrupo {
                get {
                    return this.ListaUsuarioGrupoField;
                }
                set {
                    if ((object.ReferenceEquals(this.ListaUsuarioGrupoField, value) != true)) {
                        this.ListaUsuarioGrupoField = value;
                        this.RaisePropertyChanged("ListaUsuarioGrupo");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public bool Privado {
                get {
                    return this.PrivadoField;
                }
                set {
                    if ((this.PrivadoField.Equals(value) != true)) {
                        this.PrivadoField = value;
                        this.RaisePropertyChanged("Privado");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BannerIdiomaExcecao", Namespace="http://schemas.datacontract.org/2004/07/DTO.Banner")]
    [System.SerializableAttribute()]
    public partial class BannerIdiomaExcecao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BannerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BannerIdiomaExcecaoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdiomaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResumoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BannerId {
            get {
                return this.BannerIdField;
            }
            set {
                if ((this.BannerIdField.Equals(value) != true)) {
                    this.BannerIdField = value;
                    this.RaisePropertyChanged("BannerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BannerIdiomaExcecaoId {
            get {
                return this.BannerIdiomaExcecaoIdField;
            }
            set {
                if ((this.BannerIdiomaExcecaoIdField.Equals(value) != true)) {
                    this.BannerIdiomaExcecaoIdField = value;
                    this.RaisePropertyChanged("BannerIdiomaExcecaoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdiomaId {
            get {
                return this.IdiomaIdField;
            }
            set {
                if ((this.IdiomaIdField.Equals(value) != true)) {
                    this.IdiomaIdField = value;
                    this.RaisePropertyChanged("IdiomaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Resumo {
            get {
                return this.ResumoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResumoField, value) != true)) {
                    this.ResumoField = value;
                    this.RaisePropertyChanged("Resumo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegracaoGruppo.IIntegracaoPortal")]
    public interface IIntegracaoPortal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/ListarMenu", ReplyAction="http://tempuri.org/IIntegracaoPortal/ListarMenuResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.ListaMenuResponse ListarMenu(int SiteId, int MenuTipoId, int IdiomaId, System.Nullable<int> PublicacaoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/ListarArquivos", ReplyAction="http://tempuri.org/IIntegracaoPortal/ListarArquivosResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.Arquivo[] ListarArquivos(System.Nullable<int> OwnerId, System.Nullable<int> ArquivoCategoriaId, int ArquivoCategoriaTipoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/CarregarPublicacao", ReplyAction="http://tempuri.org/IIntegracaoPortal/CarregarPublicacaoResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.Publicacao CarregarPublicacao(int SiteId, int PublicacaoId, int IdiomaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/CarregarConfiguracao", ReplyAction="http://tempuri.org/IIntegracaoPortal/CarregarConfiguracaoResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.Configuracao CarregarConfiguracao(int SiteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/CarregarTagSite", ReplyAction="http://tempuri.org/IIntegracaoPortal/CarregarTagSiteResponse")]
        string CarregarTagSite(int SiteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/CarregarBanner", ReplyAction="http://tempuri.org/IIntegracaoPortal/CarregarBannerResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.Banner CarregarBanner(int SiteId, int PublicacaoId, int BannetTipoId, int IdiomaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/CarregarArquivo", ReplyAction="http://tempuri.org/IIntegracaoPortal/CarregarArquivoResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.Arquivo CarregarArquivo(int ArquivoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegracaoPortal/CarregarHome", ReplyAction="http://tempuri.org/IIntegracaoPortal/CarregarHomeResponse")]
        PortalGalvaniMobile.IntegracaoGruppo.Publicacao CarregarHome(int SiteId, int IdiomaId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegracaoPortalChannel : PortalGalvaniMobile.IntegracaoGruppo.IIntegracaoPortal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegracaoPortalClient : System.ServiceModel.ClientBase<PortalGalvaniMobile.IntegracaoGruppo.IIntegracaoPortal>, PortalGalvaniMobile.IntegracaoGruppo.IIntegracaoPortal {
        
        public IntegracaoPortalClient() {
        }
        
        public IntegracaoPortalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegracaoPortalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoPortalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegracaoPortalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.ListaMenuResponse ListarMenu(int SiteId, int MenuTipoId, int IdiomaId, System.Nullable<int> PublicacaoId) {
            return base.Channel.ListarMenu(SiteId, MenuTipoId, IdiomaId, PublicacaoId);
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.Arquivo[] ListarArquivos(System.Nullable<int> OwnerId, System.Nullable<int> ArquivoCategoriaId, int ArquivoCategoriaTipoId) {
            return base.Channel.ListarArquivos(OwnerId, ArquivoCategoriaId, ArquivoCategoriaTipoId);
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.Publicacao CarregarPublicacao(int SiteId, int PublicacaoId, int IdiomaId) {
            return base.Channel.CarregarPublicacao(SiteId, PublicacaoId, IdiomaId);
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.Configuracao CarregarConfiguracao(int SiteId) {
            return base.Channel.CarregarConfiguracao(SiteId);
        }
        
        public string CarregarTagSite(int SiteId) {
            return base.Channel.CarregarTagSite(SiteId);
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.Banner CarregarBanner(int SiteId, int PublicacaoId, int BannetTipoId, int IdiomaId) {
            return base.Channel.CarregarBanner(SiteId, PublicacaoId, BannetTipoId, IdiomaId);
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.Arquivo CarregarArquivo(int ArquivoId) {
            return base.Channel.CarregarArquivo(ArquivoId);
        }
        
        public PortalGalvaniMobile.IntegracaoGruppo.Publicacao CarregarHome(int SiteId, int IdiomaId) {
            return base.Channel.CarregarHome(SiteId, IdiomaId);
        }
    }
}
