//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Contato {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contato() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Contato", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conosco.
        /// </summary>
        internal static string Conosco {
            get {
                return ResourceManager.GetString("Conosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMO CHEGAR.
        /// </summary>
        internal static string ContatoComoChegar {
            get {
                return ResourceManager.GetString("ContatoComoChegar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÁREA APROXIMADA(m).
        /// </summary>
        internal static string ContatoPlaceAreaAproximada {
            get {
                return ResourceManager.GetString("ContatoPlaceAreaAproximada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asfalto.
        /// </summary>
        internal static string ContatoPlaceAsfalto {
            get {
                return ResourceManager.GetString("ContatoPlaceAsfalto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASSUNTO.
        /// </summary>
        internal static string ContatoPlaceAssunto {
            get {
                return ResourceManager.GetString("ContatoPlaceAssunto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brita.
        /// </summary>
        internal static string ContatoPlaceBrita {
            get {
                return ResourceManager.GetString("ContatoPlaceBrita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDADE.
        /// </summary>
        internal static string ContatoPlaceCidade {
            get {
                return ResourceManager.GetString("ContatoPlaceCidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-MAIL.
        /// </summary>
        internal static string ContatoPlaceEmail {
            get {
                return ResourceManager.GetString("ContatoPlaceEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR.
        /// </summary>
        internal static string ContatoPlaceEnviar {
            get {
                return ResourceManager.GetString("ContatoPlaceEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loteamentos.
        /// </summary>
        internal static string ContatoPlaceLoteamentos {
            get {
                return ResourceManager.GetString("ContatoPlaceLoteamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAGEM.
        /// </summary>
        internal static string ContatoPlaceMensagem {
            get {
                return ResourceManager.GetString("ContatoPlaceMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        internal static string ContatoPlaceNome {
            get {
                return ResourceManager.GetString("ContatoPlaceNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obras.
        /// </summary>
        internal static string ContatoPlaceObras {
            get {
                return ResourceManager.GetString("ContatoPlaceObras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFONE.
        /// </summary>
        internal static string ContatoPlaceTelefone {
            get {
                return ResourceManager.GetString("ContatoPlaceTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato Rápido.
        /// </summary>
        internal static string ContatoRapido {
            get {
                return ResourceManager.GetString("ContatoRapido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone:.
        /// </summary>
        internal static string ContatoTelefone {
            get {
                return ResourceManager.GetString("ContatoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fale com a Galvani.
        /// </summary>
        internal static string ContatoTexto1 {
            get {
                return ResourceManager.GetString("ContatoTexto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContatoTexto2 {
            get {
                return ResourceManager.GetString("ContatoTexto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entraremos em contato o mais breve possvel.
        /// </summary>
        internal static string ContatoTexto3 {
            get {
                return ResourceManager.GetString("ContatoTexto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ContatoTexto4 {
            get {
                return ResourceManager.GetString("ContatoTexto4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua mensagem foi enviada com sucesso!.
        /// </summary>
        internal static string ContatoTexto5 {
            get {
                return ResourceManager.GetString("ContatoTexto5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRABALHE CONOSCO.
        /// </summary>
        internal static string ContatoTrabalheConosco {
            get {
                return ResourceManager.GetString("ContatoTrabalheConosco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se você quer desafios, aprendizado e.
        /// </summary>
        internal static string ConteudoSubTexto1 {
            get {
                return ResourceManager.GetString("ConteudoSubTexto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crescimento,.
        /// </summary>
        internal static string ConteudoSubTexto2 {
            get {
                return ResourceManager.GetString("ConteudoSubTexto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to venha para a Galvani..
        /// </summary>
        internal static string ConteudoSubTexto3 {
            get {
                return ResourceManager.GetString("ConteudoSubTexto3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galvani Engenharia sabe que uma empresa excepcional é formada por pessoas excepcionais..
        /// </summary>
        internal static string ConteudoTexto1 {
            get {
                return ResourceManager.GetString("ConteudoTexto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nossa constante avaliação de desempenho unificada e direcionada para os objetivos estratégicos da empresa estimula o crescimento pessoal e profissional de toda a equipe..
        /// </summary>
        internal static string ConteudoTexto2 {
            get {
                return ResourceManager.GetString("ConteudoTexto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-MAIL.
        /// </summary>
        internal static string CurriculoEmail {
            get {
                return ResourceManager.GetString("CurriculoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR.
        /// </summary>
        internal static string CurriculoEnviar {
            get {
                return ResourceManager.GetString("CurriculoEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENVIAR CURRICULO.
        /// </summary>
        internal static string CurriculoEnviarCurriculo {
            get {
                return ResourceManager.GetString("CurriculoEnviarCurriculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSAGEM.
        /// </summary>
        internal static string CurriculoMensagem {
            get {
                return ResourceManager.GetString("CurriculoMensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME.
        /// </summary>
        internal static string CurriculoNome {
            get {
                return ResourceManager.GetString("CurriculoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TELEFONE.
        /// </summary>
        internal static string CurriculoTelefone {
            get {
                return ResourceManager.GetString("CurriculoTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalhe.
        /// </summary>
        internal static string Trabalhe {
            get {
                return ResourceManager.GetString("Trabalhe", resourceCulture);
            }
        }
    }
}
